INSERT INTO questions (question_text, optiona, optionb, optionc, optiond, correct_answer, subject, grade_level, in_assessment) VALUES
('Hansı sırada bütün sözlər yalnız qoşmalardan ibarətdir?', 'ilə, üçün, kimi', 'ki, isə, amma', 'və, lakin, çünki', 'da, də, ta', 'A', 'AZERBAYCAN_DILI', 'GRADE_11', true),
('Hansı cümlədə xitab işlədilmişdir?', 'O evə getdi.', 'Əli, sən harada idin?', 'Hava gözəldir.', 'Kitab maraqlıdır.', 'B', 'AZERBAYCAN_DILI', 'GRADE_11', true),
('Hansı söz çoxmənalıdır?', 'kompüter', 'baş', 'stol', 'saat', 'B', 'AZERBAYCAN_DILI', 'GRADE_11', true),
('Hansı cümlə sual cümləsidir?', 'Hava gözəldir.', 'Sən harada idin?', 'Tez gəl!', 'Nə gözəl hava!', 'B', 'AZERBAYCAN_DILI', 'GRADE_11', true),
('Cümlənin hansı üzvü kimə? nəyə? sualına cavab verir?', 'Mübtəda', 'Xəbər', 'Dolayı tamamlıq', 'Zərflik', 'C', 'AZERBAYCAN_DILI', 'GRADE_11', true),
('Hansı söz alınmadır?', 'dağ', 'çay', 'kitab', 'ev', 'C', 'AZERBAYCAN_DILI', 'GRADE_11', true),
('Gözəl sözü hansı nitq hissəsinə aiddir?', 'İsim', 'Fel', 'Sifət', 'Zərf', 'C', 'AZERBAYCAN_DILI', 'GRADE_11', true),
('Hansı sözdə ahəng qanunu pozulmuşdur?', 'alma', 'kitab', 'göz', 'palıd', 'B', 'AZERBAYCAN_DILI', 'GRADE_11', true),
('Hansı cümlədə ümumiləşdirici söz işlədilmişdir?', 'Kitab, dəftər, qələm götürdüm.', 'Hər şey: kitab, dəftər, qələm hazır idi.', 'O oxudu və yazdı.', 'Uşaqlar gəldi.', 'B', 'AZERBAYCAN_DILI', 'GRADE_11', true),
('Müəllim dərsi izah etdi cümləsinin xəbəri hansı növdədir?', 'Sadə feli xəbər', 'Mürəkkəb feli xəbər', 'İsmi xəbər', 'Sifəti xəbər', 'A', 'AZERBAYCAN_DILI', 'GRADE_11', true),
('Hansı sırada bütün sözlər sinonimlər cütüdür?', 'böyük, kiçik', 'xoşbəxt, bəxtəvər', 'gec, tez', 'soyuq, isti', 'B', 'AZERBAYCAN_DILI', 'GRADE_11', true),
('Aşağıdakılardan hansı bağlayıcıdır?', 'ilə', 'üçün', 'ancaq', 'kimi', 'C', 'AZERBAYCAN_DILI', 'GRADE_11', true),
('Oxumaq feli hansı şəkildədir?', 'Xəbər şəkli', 'Əmr şəkli', 'Arzu şəkli', 'Məsdər', 'D', 'AZERBAYCAN_DILI', 'GRADE_11', true),
('Hansı cümlədə zərflik var?', 'O gözəl qızı gördü.', 'O sürətlə qaçdı.', 'Uşaq oyuncaq aldı.', 'Müəllim dərsi keçdi.', 'B', 'AZERBAYCAN_DILI', 'GRADE_11', true),
('Aşağıdakılardan hansı Azərbaycan ədəbiyyatının nümayəndəsidir?', 'Puşkin', 'Şekspir', 'Füzuli', 'Dante', 'C', 'AZERBAYCAN_DILI', 'GRADE_11', true),
('Hansı sözdə lıq/lik şəkilçisi sözdüzəldicidir?', 'günlük', 'kitabçı', 'oxucu', 'yazıçı', 'A', 'AZERBAYCAN_DILI', 'GRADE_11', false),
('Kitab oxumaq faydalıdır cümləsinin mübtədası hansıdır?', 'Kitab', 'Oxumaq', 'Kitab oxumaq', 'Faydalıdır', 'C', 'AZERBAYCAN_DILI', 'GRADE_11', false),
('Mürəkkəb cümləni sadə cümlədən fərqləndirən əsas əlamət nədir?', 'Uzun olması', 'İki və daha artıq xəbərin olması', 'Çox sözün işlənməsi', 'Mübtədanın olmaması', 'B', 'AZERBAYCAN_DILI', 'GRADE_11', false),
('Hansı sırada bütün sözlər feildən düzəlmişdir?', 'oxucu, yazıçı, çalışqan', 'gəlinti, gedinti, bitirim', 'gözəllik, xoşluq, ustalıq', 'dağlıq, meşəlik, çöllük', 'B', 'AZERBAYCAN_DILI', 'GRADE_11', false),
('Leyla çox gözəl oxuyur cümləsində gözəl hansı cümlə üzvüdür?', 'Mübtəda', 'Tamamlıq', 'Zərflik', 'Təyin', 'C', 'AZERBAYCAN_DILI', 'GRADE_11', false),
('Aşağıdakı cümlələrdən hansında işarə əvəzliyi var?', 'Mən kitab oxuyuram.', 'Bu ev bizimdir.', 'Kim gəldi?', 'Heç kəs bilmir.', 'B', 'AZERBAYCAN_DILI', 'GRADE_11', false),
('Hansı sözlər omonimlər cütü təşkil edir?', 'gəl-get', 'yaz-yaz', 'ev-ocaq', 'su-çay', 'B', 'AZERBAYCAN_DILI', 'GRADE_11', false),
('Azərbaycan dilində keçmiş zamanın neçə növü var?', '2', '3', '4', '5', 'B', 'AZERBAYCAN_DILI', 'GRADE_11', false),
('Hansı bəndli mürəkkəb cümlədir?', 'O gəldi, biz getdik.', 'Mən bildim ki, o haqlıdır.', 'Hava soyudu, çünki qış gəldi.', 'O oxudu və yazdı.', 'B', 'AZERBAYCAN_DILI', 'GRADE_11', false),
('Hansı cümlədə tərzi-hərəkət zərfliyi var?', 'O evə getdi.', 'O diqqətlə oxudu.', 'Uşaqlar parkda oynadı.', 'Hava dünən soyuq idi.', 'B', 'AZERBAYCAN_DILI', 'GRADE_11', false),
('Sead sözünün antonimi hansıdır?', 'xoşbəxtlik', 'bədbəxtlik', 'sevinc', 'həyəcan', 'B', 'AZERBAYCAN_DILI', 'GRADE_11', false),
('Hansı cümlədə işarə əvəzliyi subyekt rolunda çıxış edir?', 'Mən getdim.', 'Bu bizim evdir.', 'Heç kim gəlmədi.', 'Özüm bildim.', 'B', 'AZERBAYCAN_DILI', 'GRADE_11', false),
('Felin hansı şəkli arzu və istəyi bildirir?', 'Xəbər şəkli', 'Əmr şəkli', 'Arzu şəkli', 'Şərt şəkli', 'C', 'AZERBAYCAN_DILI', 'GRADE_11', false),
('Hansı sözdə kök və şəkilçi düzgün ayrılmışdır?', 'gözəl-lik', 'gəl-ir', 'sev-gi', 'yaz-ı', 'A', 'AZERBAYCAN_DILI', 'GRADE_11', false),
('Aşağıdakı cümlələrdən hansı məqsədinə görə əmr cümləsidir?', 'Hava gözəldir.', 'Sən harada idin?', 'Dərsinizi oxuyun!', 'Nə gözəl mənzərə!', 'C', 'AZERBAYCAN_DILI', 'GRADE_11', false);
