INSERT INTO questions (question_text, optiona, optionb, optionc, optiond, correct_answer, subject, grade_level, in_assessment) VALUES
('Choose the correct form: She ___ to school every day.', 'go', 'goes', 'going', 'gone', 'B', 'INGILIS_DILI', 'GRADE_11', true),
('Which sentence is in the Past Perfect tense?', 'She has finished her work.', 'She had finished her work before he arrived.', 'She finished her work.', 'She was finishing her work.', 'B', 'INGILIS_DILI', 'GRADE_11', true),
('Choose the correct passive form: They built this house in 1990.', 'This house is built in 1990.', 'This house was built in 1990.', 'This house has been built in 1990.', 'This house had been built in 1990.', 'B', 'INGILIS_DILI', 'GRADE_11', true),
('Which word is a synonym of "enormous"?', 'tiny', 'huge', 'average', 'narrow', 'B', 'INGILIS_DILI', 'GRADE_11', true),
('Choose the correct conditional: If I ___ rich, I would travel the world.', 'am', 'was', 'were', 'will be', 'C', 'INGILIS_DILI', 'GRADE_11', true),
('Which sentence uses the Present Perfect correctly?', 'I have seen that movie yesterday.', 'I have seen that movie.', 'I seen that movie.', 'I was seeing that movie.', 'B', 'INGILIS_DILI', 'GRADE_11', true),
('Choose the correct article: ___ Amazon is the longest river in South America.', 'A', 'An', 'The', 'No article', 'C', 'INGILIS_DILI', 'GRADE_11', true),
('What is the antonym of "ancient"?', 'old', 'modern', 'historical', 'traditional', 'B', 'INGILIS_DILI', 'GRADE_11', true),
('Choose the correct preposition: She is good ___ mathematics.', 'in', 'at', 'on', 'for', 'B', 'INGILIS_DILI', 'GRADE_11', true),
('Which sentence contains a relative clause?', 'She is beautiful.', 'The book which I bought is interesting.', 'He runs fast.', 'They went home.', 'B', 'INGILIS_DILI', 'GRADE_11', true),
('Choose the correct reported speech: He said: "I am tired."', 'He said he is tired.', 'He said he was tired.', 'He said he were tired.', 'He said he has been tired.', 'B', 'INGILIS_DILI', 'GRADE_11', true),
('Which modal verb expresses obligation?', 'might', 'could', 'must', 'would', 'C', 'INGILIS_DILI', 'GRADE_11', true),
('Choose the correct comparative form: This problem is ___ than the previous one.', 'more complicated', 'most complicated', 'complicateder', 'much complicated', 'A', 'INGILIS_DILI', 'GRADE_11', true),
('Which sentence is grammatically correct?', 'Neither of them are right.', 'Neither of them is right.', 'Neither of them were right.', 'Neither of them be right.', 'B', 'INGILIS_DILI', 'GRADE_11', true),
('What does the idiom "break the ice" mean?', 'To destroy something', 'To start a conversation', 'To feel cold', 'To make a mistake', 'B', 'INGILIS_DILI', 'GRADE_11', true),
('Choose the correct form: By the time she arrives, we ___ dinner.', 'finish', 'will finish', 'will have finished', 'finished', 'C', 'INGILIS_DILI', 'GRADE_11', false),
('Which word has the stress on the second syllable?', 'beautiful', 'photograph', 'important', 'family', 'C', 'INGILIS_DILI', 'GRADE_11', false),
('Choose the correct gerund or infinitive: I enjoy ___ books.', 'to read', 'reading', 'read', 'reads', 'B', 'INGILIS_DILI', 'GRADE_11', false),
('Which sentence is in the Third Conditional?', 'If I study, I will pass.', 'If I studied, I would pass.', 'If I had studied, I would have passed.', 'If I study, I would pass.', 'C', 'INGILIS_DILI', 'GRADE_11', false),
('What is the plural of "phenomenon"?', 'phenomenons', 'phenomenas', 'phenomena', 'phenomenes', 'C', 'INGILIS_DILI', 'GRADE_11', false),
('Choose the correct conjunction: I wanted to go out ___ it was raining heavily.', 'so', 'because', 'although', 'therefore', 'C', 'INGILIS_DILI', 'GRADE_11', false),
('Which word is a homophone of "right"?', 'write', 'light', 'bright', 'sight', 'A', 'INGILIS_DILI', 'GRADE_11', false),
('Choose the correct tag question: She works hard, ___?', 'does she', 'is she', 'doesnt she', 'isnt she', 'C', 'INGILIS_DILI', 'GRADE_11', false),
('What literary device is used in: "The wind whispered through the trees"?', 'Simile', 'Metaphor', 'Personification', 'Hyperbole', 'C', 'INGILIS_DILI', 'GRADE_11', false),
('Which sentence uses "used to" correctly?', 'I used to living here.', 'I used to live here.', 'I use to live here.', 'I am used to live here.', 'B', 'INGILIS_DILI', 'GRADE_11', false),
('Choose the word that best completes the sentence: The scientist made a remarkable ___ that changed medicine.', 'invention', 'discovery', 'creation', 'finding', 'B', 'INGILIS_DILI', 'GRADE_11', false),
('Which sentence demonstrates subject-verb agreement correctly?', 'The team are playing well.', 'The team is playing well.', 'The team were playing well.', 'The team play well.', 'B', 'INGILIS_DILI', 'GRADE_11', false),
('What does the prefix "mis-" mean in the word "misunderstand"?', 'again', 'wrongly', 'not', 'before', 'B', 'INGILIS_DILI', 'GRADE_11', false),
('Choose the correct form of the verb: He wishes he ___ more time.', 'has', 'had', 'have', 'will have', 'B', 'INGILIS_DILI', 'GRADE_11', false),
('Which sentence contains a dangling modifier?', 'Running down the street, the dog bit him.', 'Running down the street, he was bitten by the dog.', 'He was bitten by the dog while running.', 'The dog bit him while he was running.', 'A', 'INGILIS_DILI', 'GRADE_11', false);
