package com.Aga.Agali.service;

import com.Aga.Agali.config.RabbitMQConfig;
import com.Aga.Agali.dto.*;
import com.Aga.Agali.entity.*;
import com.Aga.Agali.mapper.LearningPlanMapper;
import com.Aga.Agali.repository.*;
import lombok.RequiredArgsConstructor;
import org.springframework.amqp.rabbit.core.RabbitTemplate;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.*;

@Service
@RequiredArgsConstructor
public class LearningPlanService {

    private final LearningPlanRepository planRepository;
    private final LearningPlanItemRepository itemRepository;
    private final TopicRepository topicRepository;
    private final LearningPlanMapper mapper;
    private final RabbitTemplate rabbitTemplate;

    public LearningPlanResponse createPlan(String userEmail,
                                           LearningPlanRequest request) {
        LearningPlan plan = LearningPlan.builder()
                .userEmail(userEmail)
                .gradeLevel(GradeLevel.valueOf(request.getGradeLevel()))
                .specialtyGroup(SpecialtyGroup.valueOf(request.getSpecialtyGroup()))
                .stage(request.getStage())
                .completionPercentage(0.0)
                .autoGenerated(false)
                .build();

        planRepository.save(plan);

        List<Subject> subjects = getSubjectsForStageAndGroup(
                request.getStage(),
                SpecialtyGroup.valueOf(request.getSpecialtyGroup()));

        List<LearningPlanItem> items = buildItems(plan, subjects,
                GradeLevel.valueOf(request.getGradeLevel()),
                new ArrayList<>());

        itemRepository.saveAll(items);
        return mapper.toPlanResponse(plan, items);
    }

    public void processTestResult(TestResultDto dto) {
        if (dto.getSubjectResults() == null) return;

        List<String> weakSubjects = new ArrayList<>();
        dto.getSubjectResults().forEach((subject, correct) -> {
            int total = dto.getTotalQuestions() > 0 ? dto.getTotalQuestions() : 1;
            double rate = (double) correct / total * 100;
            if (rate < 40) {
                weakSubjects.add(subject);
            }
        });

        if (weakSubjects.isEmpty()) return;

        GradeLevel gradeLevel = GradeLevel.valueOf(dto.getGradeLevel());
        SpecialtyGroup group = SpecialtyGroup.valueOf(dto.getSpecialtyGroup());

        LearningPlan plan = planRepository
                .findByUserEmailAndStage(dto.getUserEmail(), dto.getSessionType())
                .orElseGet(() -> {
                    LearningPlan newPlan = LearningPlan.builder()
                            .userEmail(dto.getUserEmail())
                            .gradeLevel(gradeLevel)
                            .specialtyGroup(group)
                            .stage(dto.getSessionType())
                            .completionPercentage(0.0)
                            .autoGenerated(true)
                            .build();
                    return planRepository.save(newPlan);
                });

        List<LearningPlanItem> items =
                itemRepository.findByLearningPlanId(plan.getId());

        items.forEach(item -> {
            String subject = item.getTopic().getSubject().name();
            if (weakSubjects.contains(subject)) {
                item.setPriority(1);
                item.setPriorityReason("Zəif fənn — test nəticəsinə görə");
                itemRepository.save(item);
            }
        });

        plan.setUpdatedAt(LocalDateTime.now());
        planRepository.save(plan);

        weakSubjects.forEach(subject -> {
            NotificationDto notification = NotificationDto.builder()
                    .studentEmail(dto.getUserEmail())
                    .teacherEmail("")
                    .message(subject + " fənnində nəticəniz zəifdir. "
                            + "Öyrənmə planınız yeniləndi.")
                    .type("WEAK_SUBJECT_ALERT")
                    .build();

            rabbitTemplate.convertAndSend(
                    RabbitMQConfig.NOTIFICATION_EXCHANGE,
                    RabbitMQConfig.NOTIFICATION_ROUTING_KEY,
                    notification);
        });
    }

    public LearningPlanResponse getPlan(String userEmail, String stage) {
        LearningPlan plan = planRepository
                .findByUserEmailAndStage(userEmail, stage)
                .orElseThrow(() -> new RuntimeException("Plan tapılmadı"));

        List<LearningPlanItem> items =
                itemRepository.findByLearningPlanId(plan.getId());

        return mapper.toPlanResponse(plan, items);
    }

    public LearningPlanResponse completeItem(Long itemId) {
        LearningPlanItem item = itemRepository.findById(itemId)
                .orElseThrow(() -> new RuntimeException("Mövzu tapılmadı"));

        item.setCompleted(true);
        itemRepository.save(item);

        LearningPlan plan = item.getLearningPlan();
        List<LearningPlanItem> allItems =
                itemRepository.findByLearningPlanId(plan.getId());

        long completedCount = allItems.stream()
                .filter(LearningPlanItem::isCompleted)
                .count();
        plan.setCompletionPercentage(
                (double) completedCount / allItems.size() * 100);
        plan.setUpdatedAt(LocalDateTime.now());
        planRepository.save(plan);

        return mapper.toPlanResponse(plan, allItems);
    }

    private List<LearningPlanItem> buildItems(LearningPlan plan,
                                              List<Subject> subjects,
                                              GradeLevel gradeLevel,
                                              List<String> weakSubjects) {
        List<LearningPlanItem> items = new ArrayList<>();

        for (Subject subject : subjects) {
            List<Topic> topics = topicRepository
                    .findBySubjectAndGradeLevelOrderByOrderIndex(subject, gradeLevel);

            boolean isWeak = weakSubjects.contains(subject.name());

            for (Topic topic : topics) {
                items.add(LearningPlanItem.builder()
                        .learningPlan(plan)
                        .topic(topic)
                        .priority(isWeak ? 1 : 2)
                        .completed(false)
                        .priorityReason(isWeak ? "Zəif fənn" : "Normal")
                        .build());
            }
        }
        return items;
    }

    private List<Subject> getSubjectsForStageAndGroup(String stage,
                                                      SpecialtyGroup group) {
        if ("BURAXILIS".equals(stage)) {
            return List.of(Subject.AZERBAYCAN_DILI,
                    Subject.RIYAZIYYAT, Subject.XARICI_DIL);
        }

        return switch (group) {
            case GROUP_1 -> List.of(Subject.KIMYA, Subject.RIYAZIYYAT,
                    Subject.FIZIKA, Subject.AZERBAYCAN_DILI, Subject.XARICI_DIL);
            case GROUP_2 -> List.of(Subject.COGRAFIYA, Subject.TARIX,
                    Subject.RIYAZIYYAT, Subject.AZERBAYCAN_DILI, Subject.XARICI_DIL);
            case GROUP_3 -> List.of(Subject.INGILIS_DILI, Subject.EDEBIYYAT,
                    Subject.TARIX, Subject.AZERBAYCAN_DILI, Subject.RIYAZIYYAT);
            case GROUP_4 -> List.of(Subject.KIMYA, Subject.FIZIKA,
                    Subject.BIOLOGIYA, Subject.AZERBAYCAN_DILI, Subject.XARICI_DIL);
            case GROUP_5 -> List.of(Subject.AZERBAYCAN_DILI,
                    Subject.RIYAZIYYAT, Subject.XARICI_DIL);
        };
    }
}